[package]
name = "dance_of_bytes"
version = "0.2.0"
edition = "2021"

[lib]
name = "dance_of_bytes"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
