[package]
name = "dance_of_bytes"
version = "0.3.1"
edition = "2021"

[lib]
name = "dance_of_bytes"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.4.2"
